spring:
  config:
    activate:
      on-profile: prod
  datasource:
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  output.ansi.enabled: always

springboot:
  jwt:
    secret: supernatural!@#
