spring:
  config:
    activate:
      on-profile: test
  h2:
    console:
      enabled: true
  datasource:
    username: sa
    password:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:zzimkong;
  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: create
  output.ansi.enabled: always

