name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Spring Boot Application Build
      run: ./gradlew build -x test

    - name: Build the Docker image
      run: docker build -t {{ secrets.DOCKERHUB_USERNAME }}/kong2 .
      
    - name: Docker Hub Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Docker Hub Publish
      run: docker push {{ secrets.DOCKERHUB_USERNAME }}/kong2
