name: Docker Image CI

on:
  push:
    tags: 
      - '**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set env
      run: echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Spring Boot Application Build
      run: ./gradlew build -x test

    - name: Build the Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64
        push: true
        tag_name: ${{ env.TAG }}
      
    - name: Docker Hub Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Docker Hub Publish
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/kong2
